_target_: dataset.CSVDataset
_partial_: true

name: bankrupcy
num_classes: 2
train_path: "data/bankrupcy/bankrupcy_train.csv"
test_path: "data/bankrupcy/bankrupcy_test.csv"
val_path: "data/bankrupcy/bankrupcy_val.csv"
