_target_: dataset.CSVDataset
_partial_: true

name: toxicity
num_classes: 2
train_path: "data/toxicity/toxicity_train.csv"
test_path: "data/toxicity/toxicity_test.csv"
val_path: "data/toxicity/toxicity_val.csv"